# Generated by Django 3.0.6 on 2020-05-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('pwd', models.CharField(max_length=32)),
                ('phone', models.CharField(default=None, max_length=11, null=True)),
                ('sex', models.IntegerField(choices=[[0, '男'], [1, '女']], default=0)),
                ('icon', models.ImageField(default='icon/default.jpg', upload_to='icon')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'old_boy_user',
            },
        ),
    ]
