# Generated by Django 3.0.6 on 2020-05-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200505_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publish',
            old_name='addres',
            new_name='address',
        ),
    ]
