# Generated by Django 3.0.6 on 2020-05-05 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200505_1226'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('name', 'publish')},
        ),
    ]
