# Generated by Django 3.0.6 on 2020-05-06 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200506_1154'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('name', 'publish')},
        ),
    ]
